# preprocessing模块  (没搞懂)
##### preprocessing 是sklearn库的一个数据预处理模块，它提供了一些实用的数据预处理函数和预处理类
* 官方文档：https://scikit-learn.org/stable/modules/preprocessing.html
* 参考： https://blog.csdn.net/lizhen8285/article/details/82713828

In [9]:
from sklearn import preprocessing
import numpy as np

In [10]:
data =np.array([[10,2.7,3.6],
             [-100,5,-2],
            [120,23,45]])

In [11]:
data

array([[  10. ,    2.7,    3.6],
       [-100. ,    5. ,   -2. ],
       [ 120. ,   23. ,   45. ]])

## scale函数  （标准化数据）
sp.scale(原始样本矩阵X, with_mean=True, with_std=True, copy=True)    
均值移除样本矩阵（转为标准正态分布-均值为0，标准差为1，默认按列axis=0）

In [12]:
preprocessing.scale(data)

array([[ 0.        , -0.83001895, -0.56930778],
       [-1.22474487, -0.57660608, -0.83646898],
       [ 1.22474487,  1.40662503,  1.40577676]])

官方文档：https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.scale.html

## minmax_scale函数(缩放范围)
sp.minmax_scale(X,feature_range=(0, 1), axis=0, copy=True)    
将数据在缩放在固定区间，默认缩放到区间 [0, 1]

In [13]:
preprocessing.minmax_scale(data)

array([[0.5       , 0.        , 0.11914894],
       [0.        , 0.11330049, 0.        ],
       [1.        , 1.        , 1.        ]])

## maxabs_scale函数（针对稀疏矩阵）
sp.maxabs_scale(X,axis=0, copy=True)        
数据的缩放比例为绝对值最大值，并保留正负号，即在区间 [-1.0, 1.0] 内。
* 唯一可用于稀疏数据 scipy.sparse的标准化 *

In [14]:
preprocessing.maxabs_scale(data)

array([[ 0.08333333,  0.1173913 ,  0.08      ],
       [-0.83333333,  0.2173913 , -0.04444444],
       [ 1.        ,  1.        ,  1.        ]])

## robust_scale函数（针对异常值）
sp.robust_scale(X,axis=0, with_centering=True, with_scaling=True,copy=True)
通过 Interquartile Range (IQR) 标准化数据，即四分之一和四分之三分位点之间

In [15]:
preprocessing.robust_scale(data)

array([[ 0.        , -0.22660099,  0.        ],
       [-1.        ,  0.        , -0.23829787],
       [ 1.        ,  1.77339901,  1.76170213]])